os: unstable
deploy: off
build: off
clone_depth: 50

matrix:
  fast_finish: true

branches:
  only:
    - master
    - /^greenkeeper-/

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: stable
      job_part: test
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test
    - nodejs_version: 5
      job_part: test
    - nodejs_version: 4
      job_part: test
    - nodejs_version: 3
      job_part: test
    - nodejs_version: 0.12
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm run %job_part%:appveyor
