branches:
  only:
    - master
    - /^greenkeeper-/

init:
  - git config --global core.autocrlf input

clone_depth: 50

environment:
  matrix:
    - nodejs_version: stable
      job_part: test
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test
    - nodejs_version: 5
      job_part: test

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g node-gyp
  - npm install -g npm-install-retry
  - npm-install-retry --wait 1000 --attempts 10 --
  - npm prune
  - npm i -g npm@latest
  - npm i

build: off
deploy: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - cmd: npm run %job_part%:appveyor

after_test:
  - npm run report-coverage
